name: company
description: "E-learning."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  toastification: ^2.1.0
  flutter_animate: ^4.5.0
  icons_plus: ^5.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  flutter_highlight: ^0.7.0
  slide_countdown: ^1.6.1
  flutter_math_fork: ^0.7.2
  linear_progress_bar: ^1.1.2
  primer_progress_bar: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lotties/
    - assets/images/
    - assets/jsons/
    #    - assets/videos/
    #    - assets/videos/imports/
    #    - assets/videos/imports/media/
    #    - assets/videos/imports/media/
    #    - assets/videos/imports/media/videos/
    #    - assets/videos/imports/media/videos/imports/
    - assets/videos/imports/media/videos/imports/1080p60/
